### ISSUE TITLE
Bilah Bantuan ( Navbar )

### ISSUE THREAD

**Issue by GanXx8** [FTP-YCAB-Fullstack/GP2-Hooks#6]
Terdapat Navbar yang berfungsi untuk menyediakan sebuah tombol pintasan untuk menuju halaman yang ingin dituju
terdapat bebrapa tombol pintasan yakni;

- [ ] Halaman Utama ( Home ) #2 
- [ ] Halaman ke Dua (  Curent Converter ) #3 
- [ ] Halaman ke Tiga ( Crypto List ) #4
